name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
permissions:
  contents: write
  security-events: write # Diperlukan untuk upload laporan security (opsional)

jobs:
  # --- JOB 1: SECURITY CHECK (Jalan Duluan) ---
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Wajib 0 buat Gitleaks ngecek history commit

      # 1. Gitleaks: Cek apakah ada API Key/Password nyasar
      - name: Detect Secrets (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Kalau step ini merah, artinya ada rahasia yang terekspos di code kamu!

      # 2. Trivy: Cek library/dependency yang bolong (Vulnerable)
      - name: Scan Filesystem with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          hide-progress: false
          format: 'table'
          exit-code: '1' # Fail action kalau ada issue critical
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  # --- JOB 2: BUILD & RELEASE (Nunggu Job 1 Selesai) ---
  build-and-release:
    needs: security-check # PENTING: Hanya jalan kalau security-check HIJAU
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      # Flutter Analyze: Cek kualitas codingan (Best Practice)
      # - name: Analyze Code
      #   run: flutter analyze

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build APK Release
        run: flutter build apk --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          generate_release_notes: true